{
 "title": "Cardano SPO - Dashboard",
 "description": "Cardano Pool Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   { "name": "DS_CSV", "label": "CSV", "query": "marcusolsson-csv-datasource" },
   { "name": "relays", "label": "Node", "query": { "query": "label_values(alias)" } }
  ]
 },
 "panels": [
  { "title": "Pool Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{alias=\"block-producer-node\"}",
     "legendFormat": "Epoch"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Block height"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Slot height"
    }
   ]
  },
  {
   "title": "Epoch Progress",
   "type": "gauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"block-producer-node\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "KES Key Rotation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int{alias=\"block-producer-node\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int{alias=\"block-producer-node\"}",
     "legendFormat": "Expiry"
    }
   ]
  },
  {
   "title": "KES Key : Days Left",
   "type": "gauge",
   "description": "Remaining KES DAYS before we need to rotate keys",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int{alias=\"block-producer-node\"} * 1.5)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((cardano_node_metrics_Forge_node_not_leader_counter{alias=\"block-producer-node\"} or cardano_node_metrics_Forge_node_not_leader_int{alias=\"block-producer-node\"}) + (cardano_node_metrics_Forge_adopted_counter{alias=\"block-producer-node\"} or cardano_node_metrics_Forge_adopted_int{alias=\"block-producer-node\"})) / (cardano_node_metrics_Forge_about_to_lead_counter{alias=\"block-producer-node\"} or cardano_node_metrics_Forge_forge_about_to_lead_int{alias=\"block-producer-node\"}) * 100",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "stat",
   "description": "Retrieved from external API data source",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "data_poolLiveDelegators{alias=\"block-producer-node\"}"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "stat",
   "description": "Retrieved from external API data source",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "data_poolLiveSaturation{alias=\"block-producer-node\"}"
    }
   ]
  },
  {
   "title": "Lifetime Blocks",
   "type": "stat",
   "description": "Retrieved from external API data source",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "data_poolBlockCount{alias=\"block-producer-node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "stat",
   "description": "Forged blocks since last restart",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_counter{alias=\"block-producer-node\"} or cardano_node_metrics_Forge_adopted_int{alias=\"block-producer-node\"} or cardano_node_metrics_blocksForged_int{alias=\"block-producer-node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Live stake",
   "type": "stat",
   "description": "Retrieved from external API data source",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(data_poolLiveStake{alias=\"block-producer-node\"}/1000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reward stake",
   "type": "stat",
   "description": "Snapshot of stake taken 2 epochs ago used for reward calculation in the current epoch",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(data_poolStakeSetAda{alias=\"block-producer-node\"}/1000000)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Retrieved from external API data source",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(data_poolPledge{alias=\"block-producer-node\"}/1000000)",
     "legendFormat": "Pool Pledge"
    },
    {
     "expr": "round(data_poolLivePledge{alias=\"block-producer-node\"}/1000000)",
     "legendFormat": "Live Pledge"
    },
    {
     "expr": "round(data_poolFixedCost{alias=\"block-producer-node\"}/1000000)",
     "legendFormat": "Fixed cost"
    },
    {
     "expr": "data_poolMargin{alias=\"block-producer-node\"}*100",
     "legendFormat": "Margin"
    }
   ]
  },
  {
   "title": "Leader schedule",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Slot"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Slot", "type": "number" }
     ]
    }
   ]
  },
  { "title": "Node - $relays", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "relays" },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_cardano_build_info{alias=\"$relays\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"$relays\"} / (1000)",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Relay Node System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "node_load1{alias=\"$relays\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"$relays\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"$relays\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Relay Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"$relays\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"$relays\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"$relays\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"$relays\"} / (node_memory_MemTotal_bytes{alias=\"$relays\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"$relays\"} / node_memory_SwapTotal_bytes{alias=\"$relays\"})) * 100",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_inboundConns_int{alias=\"$relays\"} or cardano_node_metrics_connectionManager_incomingConns{alias=\"$relays\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "TX's processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_counter{alias=\"$relays\"} or cardano_node_metrics_txsProcessedNum_int{alias=\"$relays\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  { "title": "Blockchain stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Mempool Transactions",
   "type": "timeseries",
   "description": "current",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "tx" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=~\"$relays\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block Sync Speed (blocks / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int{alias=~\"$relays\"}[150s]) *60",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{alias=~\"$relays\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=~\"$relays\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=~\"$relays\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Device stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Aggregate Data Transfer",
   "type": "timeseries",
   "description": "1 hour rolling window",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{alias=~\"$relays\"}[1h]) * 3600",
     "legendFormat": "{{alias}} - {{device}}"
    }
   ]
  },
  {
   "title": "Memory Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=~\"$relays\"} / (node_memory_MemTotal_bytes{alias=~\"$relays\"})))* 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peak Memory Allocated",
   "type": "timeseries",
   "description": "Counts only memory that is physically free (from OS, in MBytes)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{alias=~\"$relays\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Current \"Residency\" (amount of live data)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{alias=~\"$relays\"}/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Max \"Residency\"",
   "type": "timeseries",
   "description": "Amount of live data, MBytes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{alias=~\"$relays\"} /(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{alias=~\"$relays\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "RSS (allocated memory in RAM)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Mem_resident_int{alias=~\"$relays\"})/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Time Synchronization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Time Synchronization ($relays)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "repeat": "relays",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{alias=\"$relays\"}",
     "legendFormat": "Est. error(s)"
    },
    {
     "expr": "node_timex_offset_seconds{alias=\"$relays\"}",
     "legendFormat": "Offset: Node vs. Ref."
    },
    {
     "expr": "node_timex_maxerror_seconds{alias=\"$relays\"}",
     "legendFormat": "Max. Error (s)"
    }
   ]
  }
 ]
}